
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "simone-webshop/apps/api/internal/analytics"


)

var tests = []testing.InternalTest{

	{"TestBuildAlerts", _test.TestBuildAlerts},

	{"TestBuildAlertsNoBaseline", _test.TestBuildAlertsNoBaseline},

	{"TestBuildAlertsTelemetrySilence", _test.TestBuildAlertsTelemetrySilence},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "simone-webshop/apps/api/internal/analytics"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

