
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "simone-webshop/apps/api/internal/admin"


)

var tests = []testing.InternalTest{

	{"TestNormalizeChannelAuthSnapshotAcceptsBaseURL", _test.TestNormalizeChannelAuthSnapshotAcceptsBaseURL},

	{"TestNormalizeChannelAuthSnapshotRejectsMissingToken", _test.TestNormalizeChannelAuthSnapshotRejectsMissingToken},

	{"TestNormalizeChannelAuthSnapshotRejectsInvalidEndpoint", _test.TestNormalizeChannelAuthSnapshotRejectsInvalidEndpoint},

	{"TestChannelProfileHasRequiredFields", _test.TestChannelProfileHasRequiredFields},

	{"TestIsAllowedKillSwitchDomain", _test.TestIsAllowedKillSwitchDomain},

	{"TestScoreItemComparators", _test.TestScoreItemComparators},

	{"TestPickRevenueScenario", _test.TestPickRevenueScenario},

	{"TestMergeRevenueForecastPolicyPatch", _test.TestMergeRevenueForecastPolicyPatch},

	{"TestMergeRevenueScenarioBounds", _test.TestMergeRevenueScenarioBounds},

	{"TestNormalizeChannelsFiltersAndDedupes", _test.TestNormalizeChannelsFiltersAndDedupes},

	{"TestNormalizeCountryScope", _test.TestNormalizeCountryScope},

	{"TestResolveTrendDecision", _test.TestResolveTrendDecision},

	{"TestMergeTrendPolicyAppliesPatch", _test.TestMergeTrendPolicyAppliesPatch},

	{"TestParseCategoryPoliciesPatch", _test.TestParseCategoryPoliciesPatch},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "simone-webshop/apps/api/internal/admin"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

